<a href="https://colab.research.google.com/github/ashbyp/mltorch/blob/master/colab/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Introduction

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.12.0+cu113


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [6]:
vector.ndim
vector.shape

torch.Size([3])

In [7]:
MATRIX = torch.tensor([[7,8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
MATRIX[0]


tensor([7, 8])

In [11]:
MATRIX[1][1]


tensor(10)

In [12]:
TENSOR = torch.tensor([[[[1,2,3, 5], [4,5,6,5], [9,3,1,5]]]])
TENSOR

tensor([[[[1, 2, 3, 5],
          [4, 5, 6, 5],
          [9, 3, 1, 5]]]])

In [13]:
TENSOR.shape

torch.Size([1, 1, 3, 4])

Random

In [14]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1689, 0.4954, 0.7375, 0.2446],
        [0.0894, 0.1784, 0.4262, 0.7115],
        [0.9045, 0.6578, 0.6716, 0.2669]])

In [15]:
random_tensor.shape

torch.Size([3, 4])

In [16]:
random_tensor.ndim

2

In [17]:
img = torch.rand(size=(224, 224, 3))

In [18]:
img.shape

torch.Size([224, 224, 3])

In [19]:
img.ndim

3

In [20]:
img = torch.rand(224, 224, 3)
img.shape, img.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
zeros=zero
zeros*ones
ones+ones

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [25]:
torch.range(1, 10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  """Entry point for launching an IPython kernel.


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [27]:
x = torch.arange(1, 10)
x
y = torch.zeros_like(x)
y
y.dtype

torch.int64

In [28]:
z = y.type(torch.half)
z.device

device(type='cpu')

In [29]:
x = torch.rand(2, 2)
print(x)
print(x*2)
print(x*x)


tensor([[0.0515, 0.1546],
        [0.7772, 0.2718]])
tensor([[0.1029, 0.3091],
        [1.5544, 0.5436]])
tensor([[0.0026, 0.0239],
        [0.6040, 0.0739]])


## Tensor Operations
* addition
* subtraction
* multiplication
* division
* matrix multipliacation

In [30]:
x = torch.tensor([1,2,3])
x + 10

tensor([11, 12, 13])

In [31]:
x * 10

tensor([10, 20, 30])

In [32]:
x - 10

tensor([-9, -8, -7])

In [33]:
torch.mul(x, 10)

tensor([10, 20, 30])

In [34]:
x = torch.tensor([[1, 2], [3, 4]])
x


tensor([[1, 2],
        [3, 4]])

In [35]:
x


tensor([[1, 2],
        [3, 4]])

In [36]:
a = torch.arange(1, 11)
a.min(), a.max(), a.type(torch.float64).mean(), a.sum(), a.argmax(), a.argmin()


(tensor(1),
 tensor(10),
 tensor(5.5000, dtype=torch.float64),
 tensor(55),
 tensor(9),
 tensor(0))

In [37]:
a


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
a.reshape(2,5)


tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [39]:
a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
a.reshape(10, 1)

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])

In [41]:
a = torch.arange(1, 10)
a, a.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [42]:
b = a.view(3, 3)
a, a.shape, b, b.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]), tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]), torch.Size([3, 3]))

In [43]:
a[0] = 1111

In [44]:
a, b

(tensor([1111,    2,    3,    4,    5,    6,    7,    8,    9]),
 tensor([[1111,    2,    3],
         [   4,    5,    6],
         [   7,    8,    9]]))

In [45]:
a

tensor([1111,    2,    3,    4,    5,    6,    7,    8,    9])

In [46]:
s = torch.stack([a,a], dim=1)

In [47]:
s

tensor([[1111, 1111],
        [   2,    2],
        [   3,    3],
        [   4,    4],
        [   5,    5],
        [   6,    6],
        [   7,    7],
        [   8,    8],
        [   9,    9]])

In [48]:
x = torch.zeros(5, 1, 4, 1, 3)
x

tensor([[[[[0., 0., 0.]],

          [[0., 0., 0.]],

          [[0., 0., 0.]],

          [[0., 0., 0.]]]],



        [[[[0., 0., 0.]],

          [[0., 0., 0.]],

          [[0., 0., 0.]],

          [[0., 0., 0.]]]],



        [[[[0., 0., 0.]],

          [[0., 0., 0.]],

          [[0., 0., 0.]],

          [[0., 0., 0.]]]],



        [[[[0., 0., 0.]],

          [[0., 0., 0.]],

          [[0., 0., 0.]],

          [[0., 0., 0.]]]],



        [[[[0., 0., 0.]],

          [[0., 0., 0.]],

          [[0., 0., 0.]],

          [[0., 0., 0.]]]]])

In [49]:
x.squeeze()

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [50]:
a = torch.tensor([[[1,2,3], [4,5,6]]])
a, a.shape

(tensor([[[1, 2, 3],
          [4, 5, 6]]]), torch.Size([1, 2, 3]))

In [51]:
a[0]


tensor([[1, 2, 3],
        [4, 5, 6]])

In [52]:
a[0,1]

tensor([4, 5, 6])

In [53]:
a[0,1,1:]

tensor([5, 6])

In [54]:
a[:, 1]

tensor([[4, 5, 6]])

In [55]:
!nvidia-smi


NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [56]:
import torch
torch.cuda.is_available()

False

In [57]:
device = 'cuda'


In [58]:
torch.cuda.device_count()

0

In [59]:
a = torch.tensor([1,2,3])
a, a.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
tg = a.to('cuda')
tg, tg.device

In [ ]:
th = tg*2

In [ ]:
tg, th

In [ ]:
tg.to('cpu')


In [ ]:
tg